/********************************************************************************************
 *    _ ____  ___             _         _     ___              _                        _
 *   (_)__ / | _ \_ _ ___  __| |_  _ __| |_  |   \ _____ _____| |___ _ __ _ __  ___ _ _| |_
 *   | ||_ \ |  _/ '_/ _ \/ _` | || / _|  _| | |) / -_) V / -_) / _ \ '_ \ '  \/ -_) ' \  _|
 *   |_|___/ |_| |_| \___/\__,_|\_,_\__|\__| |___/\___|\_/\___|_\___/ .__/_|_|_\___|_||_\__|
 *                                                                  |_|
 *                           -----------------------------------
 *                          Copyright i3 Product Development 2023
 *
 * MIT License
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * \brief A minimal implementation of Reach data access.  Auto-generated by a Python script.
 *
 * Original Author: Chuck Peplinski
 * Script Author: Joseph Peplinski
 *
 * Generated with version 0.0.1 of c_code_generator.py
 *
 ********************************************************************************************/

#ifndef _DEFINITIONS_H
#define _DEFINITIONS_H

#include "reach.pb.h"

#define INCLUDE_PARAMETER_SERVICE
#define NUM_PARAMS                11
#define NUM_EX_PARAMS             2
#define INCLUDE_FILE_SERVICE
#define NUM_FILES                 3
#define INCLUDE_COMMAND_SERVICE
#define NUM_COMMANDS              4
#define INCLUDE_CLI_SERVICE
#define INCLUDE_TIME_SERVICE

typedef enum {
    PARAM_USER_DEVICE_NAME,
    PARAM_TIMEZONE_ENABLED,
    PARAM_TIMEZONE_OFFSET,
    PARAM_BT_DEVICE_ADDRESS,
    PARAM_UPTIME,
    PARAM_BUTTON_PRESSED,
    PARAM_IDENTIFY_LED_ON,
    PARAM_RGB_LED_STATE,
    PARAM_RGB_LED_COLOR,
    PARAM_IDENTIFY,
    PARAM_IDENTIFY_INTERVAL,
} param_t;

typedef enum {
    RGB_LED_COLOR_OFF,
    RGB_LED_COLOR_RED,
    RGB_LED_COLOR_GREEN,
    RGB_LED_COLOR_YELLOW,
    RGB_LED_COLOR_BLUE,
    RGB_LED_COLOR_MAGENTA,
    RGB_LED_COLOR_CYAN,
    RGB_LED_COLOR_WHITE,
} rgb_led_color_t;

typedef enum {
    RGB_LED_STATE_BIT_RED   = (0x1 << 0),
    RGB_LED_STATE_BIT_GREEN = (0x1 << 1),
    RGB_LED_STATE_BIT_BLUE  = (0x1 << 2),
} rgb_led_state_t;

typedef enum {
    FILE_OTA_BIN,
    FILE_IO_TXT,
    FILE_CYGNUS_REACH_LOGO_PNG,
} file_t;

typedef enum {
    COMMAND_REBOOT,
    COMMAND_RESET_DEFAULTS,
    COMMAND_INVALIDATE_OTA_IMAGE,
    COMMAND_CLICK_FOR_WISDOM,
} command_t;

extern cr_ParameterValue sCr_param_val[NUM_PARAMS];
extern cr_ParameterInfo param_desc[NUM_PARAMS];
extern cr_ParamExInfoResponse param_ex_desc[NUM_EX_PARAMS];
extern cr_FileInfo file_descriptions[NUM_FILES];
extern cr_CommandInfo command_desc[NUM_COMMANDS];

int app_handle_param_repo_pre_init(void);
int app_handle_param_repo_init(cr_ParameterValue *data, cr_ParameterInfo *desc);
int app_handle_param_repo_post_init(void);
int app_handle_param_repo_read(cr_ParameterValue *data);
int app_handle_param_repo_write(cr_ParameterValue *data);

#endif // _DEFINITIONS_H